services:
  backend:
    build: ./doman_back
    ports:
      - "${PORT}:5000"
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
    networks:
      - doman-network

  frontend:
    build: ./doman_front
    command: sh -c "until nc -z backend 5000; do sleep 1; done && npm run build && npm run start"
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      backend:
        condition: service_started
    restart: on-failure
    networks:
      - doman-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    networks:
      - doman-network

  nginx:
    container_name: nginx-service
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./doman_back/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./doman_front/build:/var/www/html
    depends_on:
      - frontend
      - backend
    restart: on-failure
    networks:
      - doman-network

volumes:
  postgres-data:

networks:
  doman-network:
    driver: bridge